# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/CS/Desktop/project/project.cache/wt [current_project]
set_property parent.project_path C:/Users/CS/Desktop/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/xadc_wiz_0.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/ADC_sampler.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/new/Display_conv.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/switch_debouncer.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/FSM_inc_dec.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/clock_divider.v
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/SCOPE_TOP.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/clk_wiz_0_clk_wiz.vhd
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/vga_ctrl.vhd
  C:/Users/CS/Desktop/project/project.srcs/sources_1/imports/skeleton_sources/clk_wiz_0.vhd
}
read_xdc C:/Users/CS/Desktop/project/project.srcs/constrs_1/imports/skeleton_sources/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/CS/Desktop/project/project.srcs/constrs_1/imports/skeleton_sources/Basys3_Master.xdc]

synth_design -top SCOPE_TOP -part xc7a35tcpg236-3
write_checkpoint -noxdef SCOPE_TOP.dcp
catch { report_utilization -file SCOPE_TOP_utilization_synth.rpt -pb SCOPE_TOP_utilization_synth.pb }
